import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';
import { RoomEnvironment } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/environments/RoomEnvironment.js';
const $=id=>document.getElementById(id),canvas=$('scene'),loading=$('loading'),loadStatus=$('loadStatus'),entry=$('entry'),panel=$('languagePanel'),screenTitle=$('screenTitle');
const languages=[
{id:'python',name:'Python',icon:'python/python-original.svg',color:'#ffd85b',category:'GENERAL • AI • DATA',desc:'پایتون زبانی خوانا و چندمنظوره است که برای هوش مصنوعی، یادگیری ماشین، علم داده، اتوماسیون، بک‌اند وب و اسکریپت‌نویسی بسیار پرکاربرد است.',tags:['هوش مصنوعی','علم داده','Backend','Automation']},
{id:'javascript',name:'JavaScript',icon:'javascript/javascript-original.svg',color:'#f7df1e',category:'WEB • FULL STACK',desc:'جاوااسکریپت زبان اصلی تعامل در وب است؛ از رابط‌های کاربری مرورگر تا سرور با Node.js، اپلیکیشن‌های موبایل و تجربه‌های سه‌بعدی WebGL استفاده می‌شود.',tags:['Frontend','Node.js','WebGL','Mobile']},
{id:'typescript',name:'TypeScript',icon:'typescript/typescript-original.svg',color:'#4d9dff',category:'WEB • LARGE APPS',desc:'تایپ‌اسکریپت نسخه type-safe جاوااسکریپت است و برای پروژه‌های بزرگ وب، React، Angular و بک‌اندهای مدرن بسیار مناسب است.',tags:['Frontend','Backend','Type Safety','Enterprise']},
{id:'cpp',name:'C++',icon:'cplusplus/cplusplus-original.svg',color:'#6295cb',category:'SYSTEMS • GAMES',desc:'سی‌پلاس‌پلاس برای موتورهای بازی، گرافیک، شبیه‌سازی، رباتیک، سیستم‌های نهفته و نرم‌افزارهای بسیار سریع کاربرد دارد.',tags:['Game Engine','Robotics','Graphics','Systems']},
{id:'csharp',name:'C#',icon:'csharp/csharp-original.svg',color:'#9b5cff',category:'GAMES • .NET',desc:'سی‌شارپ زبان اصلی اکوسیستم .NET و از مهم‌ترین زبان‌ها برای Unity، وب‌سرویس‌ها و نرم‌افزارهای دسکتاپ است.',tags:['Unity','Game Dev','.NET','Desktop']},
{id:'java',name:'Java',icon:'java/java-original.svg',color:'#ff704d',category:'ENTERPRISE • ANDROID',desc:'جاوا در سامانه‌های سازمانی، بک‌اندهای مقیاس‌پذیر، سرویس‌های بزرگ و بسیاری از پروژه‌های اندرویدی استفاده می‌شود.',tags:['Enterprise','Backend','Android','Cloud']},
{id:'swift',name:'Swift',icon:'swift/swift-original.svg',color:'#ff674d',category:'APPLE • IOS',desc:'سوئیفت زبان مدرن اپل برای ساخت اپلیکیشن‌های iPhone، iPad، Mac، Apple Watch و visionOS است.',tags:['iOS','macOS','SwiftUI','visionOS']},
{id:'kotlin',name:'Kotlin',icon:'kotlin/kotlin-original.svg',color:'#b06cff',category:'ANDROID • JVM',desc:'کاتلین زبان مدرن توسعه اندروید است و برای Kotlin Multiplatform و بک‌اند JVM نیز استفاده می‌شود.',tags:['Android','KMP','Backend','JVM']},
{id:'go',name:'Go',icon:'go/go-original-wordmark.svg',color:'#59d7e8',category:'CLOUD • BACKEND',desc:'Go برای سرویس‌های ابری، APIهای سریع، DevOps، شبکه و سیستم‌های همزمان بسیار مناسب است.',tags:['Cloud','DevOps','Backend','Networking']},
{id:'rust',name:'Rust',icon:'rust/rust-original.svg',color:'#f09161',category:'SYSTEMS • SAFE',desc:'Rust برای برنامه‌نویسی سطح سیستم با سرعت بالا و ایمنی حافظه، WebAssembly و Embedded کاربرد دارد.',tags:['Systems','WebAssembly','Embedded','Performance']},
{id:'php',name:'PHP',icon:'php/php-original.svg',color:'#8e92d8',category:'WEB • SERVER',desc:'PHP برای بک‌اند وب، WordPress، فروشگاه‌ها و سامانه‌های مدیریت محتوا کاربرد گسترده‌ای دارد.',tags:['Web','WordPress','Backend','CMS']},
{id:'dart',name:'Dart',icon:'dart/dart-original.svg',color:'#49c7f0',category:'FLUTTER • CROSS PLATFORM',desc:'Dart زبان اصلی Flutter است و برای ساخت اپلیکیشن‌های موبایل، وب و دسکتاپ چندسکویی استفاده می‌شود.',tags:['Flutter','Mobile','Web','Cross-platform']}
];
let scene,camera,renderer,controls,laptop,screenGroup,screenTarget,laptopMode=false,activeCard=null,hoveredCard=null,cameraTween=null,audioCtx=null,musicTimer=null,musicOn=false,ambientMaster=null;
const clock=new THREE.Clock(),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),interactiveCards=[],cardPickMeshes=[],steam=[],floaters=[],readyTasks=[];
const initialCam=new THREE.Vector3(6.9,4.4,8.4),initialTarget=new THREE.Vector3(0,1.55,0),laptopCam=new THREE.Vector3(0,2.14,3.35),laptopTarget=new THREE.Vector3(0,2.05,-.32);
try{init()}catch(e){console.error(e);$('fallback').classList.remove('hidden');loading.classList.add('done')}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color('#10091d');scene.fog=new THREE.FogExp2('#10091d',.028);camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.05,80);camera.position.copy(initialCam);renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;const pm=new THREE.PMREMGenerator(renderer);scene.environment=pm.fromScene(new RoomEnvironment(),.04).texture;pm.dispose();controls=new OrbitControls(camera,canvas);controls.target.copy(initialTarget);controls.enableDamping=true;controls.dampingFactor=.055;controls.minDistance=4.5;controls.maxDistance=13;controls.minPolarAngle=.72;controls.maxPolarAngle=1.48;controls.enablePan=false;buildLighting();buildCafe();buildLaptop();buildAtmosphere();loadReadyMadeProps();bindEvents();camera.lookAt(initialTarget);animate();Promise.race([Promise.allSettled(readyTasks),new Promise(r=>setTimeout(r,7000))]).then(()=>{loadStatus.textContent='کافه آماده است';setTimeout(()=>{loading.classList.add('done');entry.classList.add('visible')},350)})}
function mat(c,r=.55,m=.08){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m})}function box(w,h,d,ma,x=0,y=0,z=0){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),ma);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;return o}
function buildLighting(){scene.add(new THREE.HemisphereLight('#ffe9d7','#17101e',1.15));const sun=new THREE.DirectionalLight('#fff0d5',3.4);sun.position.set(4,7,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);[['#ff9a68',18,-4,3,-2],['#55dfff',10,4,2.5,-3],['#ffd08b',22,0,4.7,1]].forEach(a=>{const l=new THREE.PointLight(a[0],a[1],10,2);l.position.set(a[2],a[3],a[4]);scene.add(l)})}
function buildCafe(){const floor=box(13,.18,11,mat('#261b22',.82),0,-.1,0);scene.add(floor);scene.add(box(12,5.3,.28,mat('#332326',.82),0,2.35,-4.5));scene.add(box(.25,5.3,9,mat('#241b22',.82),-6,2.35,0));
// wood wall slats and shelves
for(let i=0;i<18;i++)scene.add(box(.045,3.7,.06,mat(i%2?'#6a4333':'#503126',.7),-5.3+i*.62,2.05,-4.31));
const shelf=box(4.7,.12,.42,mat('#8a5a3b',.34),-3.1,2.45,-4.0);scene.add(shelf);for(let i=0;i<9;i++){const jar=new THREE.Mesh(new THREE.CylinderGeometry(.1,.12,.36,18),new THREE.MeshPhysicalMaterial({color:['#9b5948','#d6a65f','#6b9c72'][i%3],roughness:.25,clearcoat:.35}));jar.position.set(-5+i*.46,2.68,-3.98);scene.add(jar)}
// bar
scene.add(box(4.8,1.12,.95,mat('#4b302a',.45),-3.2,.54,-2.8));scene.add(box(5,.13,1.08,mat('#9a603c',.25),-3.2,1.16,-2.8));for(let i=0;i<5;i++){const stool=new THREE.Group(),seat=new THREE.Mesh(new THREE.CylinderGeometry(.3,.3,.1,32),mat('#6b342c',.42));seat.position.y=.72;stool.add(seat);const leg=new THREE.Mesh(new THREE.CylinderGeometry(.055,.07,.7,16),mat('#201d20',.3,.65));leg.position.y=.35;stool.add(leg);stool.position.set(-4.8+i*.85,0,-1.95);scene.add(stool)}
// main realistic wood table
const top=new THREE.Mesh(new THREE.CylinderGeometry(2.18,2.18,.16,64),new THREE.MeshPhysicalMaterial({color:'#70442f',roughness:.28,metalness:.02,clearcoat:.32,clearcoatRoughness:.2}));top.position.set(0,.82,.15);top.castShadow=top.receiveShadow=true;scene.add(top);const edge=new THREE.Mesh(new THREE.TorusGeometry(2.1,.065,16,64),mat('#3d241d',.34));edge.rotation.x=Math.PI/2;edge.position.set(0,.79,.15);scene.add(edge);const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(.3,.52,.9,32),mat('#201d20',.25,.72));pedestal.position.set(0,.34,.15);scene.add(pedestal);
// cup with wall thickness, coffee, saucer, spoon, napkin
const saucer=new THREE.Mesh(new THREE.CylinderGeometry(.5,.54,.045,64),new THREE.MeshPhysicalMaterial({color:'#eee3d6',roughness:.2,clearcoat:.65}));saucer.position.set(-1.3,.96,1.02);scene.add(saucer);const cup=new THREE.Mesh(new THREE.CylinderGeometry(.34,.28,.54,64,1,true),new THREE.MeshPhysicalMaterial({color:'#f2e5d8',roughness:.18,clearcoat:.75,side:THREE.DoubleSide}));cup.position.set(-1.3,1.24,1.02);scene.add(cup);const rim=new THREE.Mesh(new THREE.TorusGeometry(.335,.025,12,64),mat('#fff8ef',.2));rim.rotation.x=Math.PI/2;rim.position.set(-1.3,1.51,1.02);scene.add(rim);const coffee=new THREE.Mesh(new THREE.CircleGeometry(.305,64),new THREE.MeshPhysicalMaterial({color:'#2b120a',roughness:.18,clearcoat:.7}));coffee.rotation.x=-Math.PI/2;coffee.position.set(-1.3,1.505,1.02);scene.add(coffee);const handle=new THREE.Mesh(new THREE.TorusGeometry(.23,.045,14,40,Math.PI*1.55),mat('#f2e5d8',.2));handle.rotation.set(Math.PI/2,0,-Math.PI/2);handle.position.set(-.98,1.25,1.02);scene.add(handle);const spoon=box(.035,.018,.62,mat('#c7c2ba',.16,.8),-1.72,1.01,.9);spoon.rotation.y=-.35;scene.add(spoon);const napkin=box(.62,.018,.5,mat('#b87864',.85),1.42,.94,1.2);napkin.rotation.y=.25;scene.add(napkin);
// secondary cafe tables
[[-3.8,1.6],[3.8,1.3],[4,-2.1]].forEach(([x,z],n)=>{const t=new THREE.Mesh(new THREE.CylinderGeometry(.8,.8,.1,48),mat(n%2?'#81503a':'#70412f',.34));t.position.set(x,.75,z);scene.add(t);const l=new THREE.Mesh(new THREE.CylinderGeometry(.12,.2,.72,20),mat('#262226',.3,.6));l.position.set(x,.36,z);scene.add(l);const tinyCup=new THREE.Mesh(new THREE.CylinderGeometry(.13,.11,.22,32),mat('#eee4d8',.25));tinyCup.position.set(x+.22,.92,z-.08);scene.add(tinyCup)});
// menu board and pendant lamps
const tex=makeTextTexture('CODE  +  COFFEE','#ffe5a0','#2a171d',1024,260),sign=new THREE.Mesh(new THREE.PlaneGeometry(3.5,.9),new THREE.MeshBasicMaterial({map:tex,toneMapped:false}));sign.position.set(.7,3.9,-4.12);scene.add(sign);[-2.4,0,2.4].forEach((x,i)=>{scene.add(box(.025,1,.025,mat('#181519',.4,.7),x,4.8,-.4));const sh=new THREE.Mesh(new THREE.ConeGeometry(.4,.4,32,1,true),mat(['#8c4e38','#b07a3f','#476d67'][i],.3));sh.position.set(x,4.18,-.4);sh.rotation.x=Math.PI;scene.add(sh);const bulb=new THREE.Mesh(new THREE.SphereGeometry(.09,20,20),new THREE.MeshBasicMaterial({color:'#ffdca0'}));bulb.position.set(x,4,-.4);scene.add(bulb)});
// plants
[[4.8,-3.3],[-5,2.5]].forEach(([x,z])=>{const pot=new THREE.Mesh(new THREE.CylinderGeometry(.42,.32,.62,24),mat('#9c5d47',.6));pot.position.set(x,.3,z);scene.add(pot);for(let i=0;i<10;i++){const leaf=new THREE.Mesh(new THREE.SphereGeometry(.12,16,12),mat(i%2?'#467d54':'#609a61',.72));leaf.scale.set(.75,3,.5);const a=i/10*Math.PI*2;leaf.position.set(x+Math.cos(a)*.3,.95+Math.sin(i)*.12,z+Math.sin(a)*.3);leaf.rotation.z=Math.cos(a)*.5;scene.add(leaf)}})}
function makeTextTexture(text,fg='#fff',bg='transparent',w=1024,h=512){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');if(bg!=='transparent'){x.fillStyle=bg;x.fillRect(0,0,w,h)}x.textAlign='center';x.textBaseline='middle';x.font=`700 ${Math.round(h*.32)}px Space Grotesk,Arial`;x.fillStyle=fg;x.shadowColor=fg;x.shadowBlur=20;x.fillText(text,w/2,h/2);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function buildLaptop(){laptop=new THREE.Group();laptop.position.set(0,1.02,-.15);scene.add(laptop);const aluminium=new THREE.MeshPhysicalMaterial({color:'#34323d',roughness:.24,metalness:.72,clearcoat:.25}),dark=mat('#15131b',.33,.35);laptop.add(box(3.45,.16,2.18,aluminium,0,.05,.42));laptop.add(box(3.12,.04,1.82,dark,0,.15,.34));laptop.add(box(1.35,.025,.66,mat('#4e4b56',.26,.58),0,.18,.92));for(let r=0;r<5;r++)for(let c=0;c<12;c++){if(r===4&&(c<3||c>8))continue;laptop.add(box(c===5&&r===4?.88:.19,.035,.17,mat('#222029',.42,.2),(c-5.5)*.245,.18,-.22+r*.22))}laptop.add(box(3,.12,.14,mat('#1d1b22',.28,.6),0,.2,-.62));screenGroup=new THREE.Group();screenGroup.position.set(0,1.23,-.66);screenGroup.rotation.x=-.055;laptop.add(screenGroup);screenGroup.add(box(3.48,2.2,.13,aluminium));screenGroup.add(box(3.2,1.91,.035,new THREE.MeshPhysicalMaterial({color:'#100e20',roughness:.18,clearcoat:1}),0,0,.085));const glow=new THREE.Mesh(new THREE.PlaneGeometry(3.12,1.83),new THREE.MeshBasicMaterial({color:'#231346',transparent:true,opacity:.66,toneMapped:false}));glow.position.z=.108;screenGroup.add(glow);screenTarget=new THREE.Mesh(new THREE.PlaneGeometry(3.25,1.95),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}));screenTarget.position.z=.13;screenTarget.userData.isScreen=true;screenGroup.add(screenTarget);createLanguageCards()}
function createLanguageCards(){const tl=new THREE.TextureLoader();tl.setCrossOrigin('anonymous');languages.forEach((lang,i)=>{const g=new THREE.Group(),col=i%4,row=Math.floor(i/4);g.position.set((col-1.5)*.75,(1-row)*.56,.16);g.userData={languageId:lang.id,isCard:true,baseY:g.position.y};const body=new THREE.Mesh(new THREE.BoxGeometry(.66,.47,.075),new THREE.MeshPhysicalMaterial({color:new THREE.Color(lang.color).multiplyScalar(.34),roughness:.26,metalness:.18,clearcoat:.55}));body.userData.languageId=lang.id;g.add(body);const pick=new THREE.Mesh(new THREE.PlaneGeometry(.66,.47),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false,side:THREE.DoubleSide}));pick.position.z=.052;pick.userData={languageId:lang.id,card:g};g.add(pick);cardPickMeshes.push(pick);const im=new THREE.MeshBasicMaterial({transparent:true,toneMapped:false}),icon=new THREE.Mesh(new THREE.PlaneGeometry(.23,.23),im);icon.position.set(-.16,.035,.054);g.add(icon);tl.load(`https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/${lang.icon}`,t=>{t.colorSpace=THREE.SRGBColorSpace;im.map=t;im.needsUpdate=true});const label=new THREE.Mesh(new THREE.PlaneGeometry(.34,.13),new THREE.MeshBasicMaterial({map:makeLabelTexture(lang.name),transparent:true,toneMapped:false}));label.position.set(.13,-.02,.054);g.add(label);screenGroup.add(g);interactiveCards.push(g);floaters.push(g)})}
function makeLabelTexture(text){const c=document.createElement('canvas');c.width=512;c.height=180;const x=c.getContext('2d');x.fillStyle='#fff';x.textAlign='center';x.textBaseline='middle';x.font=`700 ${text.length>9?54:66}px Space Grotesk,Arial`;x.fillText(text,256,90);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function buildAtmosphere(){for(let i=0;i<26;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.018,8,8),new THREE.MeshBasicMaterial({color:'#fff3e8',transparent:true,opacity:0}));p.position.set(-1.3+(Math.random()-.5)*.12,1.55+Math.random()*.8,1.02+(Math.random()-.5)*.08);p.userData.offset=Math.random();scene.add(p);steam.push(p)}const count=120,pos=new Float32Array(count*3);for(let i=0;i<count;i++){pos[i*3]=(Math.random()-.5)*14;pos[i*3+1]=Math.random()*5.5;pos[i*3+2]=(Math.random()-.5)*10}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));const dust=new THREE.Points(geo,new THREE.PointsMaterial({size:.018,color:'#ffd8aa',transparent:true,opacity:.35,depthWrite:false}));dust.userData.dust=true;scene.add(dust);floaters.push(dust)}
function loadReadyMadeProps(){const loader=new GLTFLoader(),load=(url,setup,label)=>{loadStatus.textContent=label;readyTasks.push(new Promise(resolve=>{let done=false;const finish=()=>{if(!done){done=true;resolve()}};setTimeout(finish,6000);loader.load(url,g=>{if(!done){try{setup(g.scene)}catch(e){console.warn(e)}finish()}},undefined,e=>{console.warn(e);finish()})}))};const chair='https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/SheenChair/glTF-Binary/SheenChair.glb';load(chair,m=>{prepareModel(m);m.scale.setScalar(1.05);m.position.set(2.25,0,.05);m.rotation.y=-2.3;scene.add(m);const a=m.clone();a.position.set(-2.05,0,1.65);a.rotation.y=.65;scene.add(a);const b=m.clone();b.position.set(4.55,0,1.1);b.rotation.y=-1.5;scene.add(b)},'چیدن صندلی‌های کافه');const lantern='https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/Lantern/glTF-Binary/Lantern.glb';load(lantern,m=>{prepareModel(m);m.scale.setScalar(.25);m.position.set(3.8,1.1,-2.8);scene.add(m)},'افزودن دکور سه‌بعدی')}
function prepareModel(r){r.traverse(o=>{if(o.isMesh)o.castShadow=o.receiveShadow=true})}
function bindEvents(){addEventListener('resize',onResize);canvas.addEventListener('pointermove',onPointerMove);canvas.addEventListener('pointerup',onPointerUp);$('focusLaptop').onclick=enterLaptop;$('homeBtn').onclick=leaveLaptop;$('closePanel').onclick=()=>panel.classList.remove('open');$('enterBtn').onclick=()=>{entry.classList.remove('visible');startMusic()};$('musicBtn').onclick=toggleMusic}
function setPointer(e){const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1}
function pickLanguage(e){setPointer(e);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(cardPickMeshes,false);if(!hits.length)return null;const h=hits[0].object;return {id:h.userData.languageId,card:h.userData.card}}
function onPointerMove(e){if(!laptopMode)return;const hit=pickLanguage(e),card=hit?.card||null;if(hoveredCard!==card){if(hoveredCard)hoveredCard.userData.hover=false;hoveredCard=card;if(card)card.userData.hover=true}canvas.style.cursor=hit?'pointer':'grab'}
function onPointerUp(e){if(laptopMode){const hit=pickLanguage(e);if(hit){showLanguage(hit.id,hit.card);return}}setPointer(e);raycaster.setFromCamera(pointer,camera);if(raycaster.intersectObject(screenTarget,false).length)enterLaptop()}
function enterLaptop(){laptopMode=true;panel.classList.remove('open');$('hero').classList.add('hidden-ui');$('hint').classList.add('hidden-ui');$('homeBtn').classList.remove('hidden');screenTitle.classList.add('visible');controls.enabled=false;tweenCamera(laptopCam,laptopTarget,1.15,()=>{controls.target.copy(laptopTarget);controls.minDistance=2.4;controls.maxDistance=4.8;controls.minPolarAngle=1.05;controls.maxPolarAngle=1.45;controls.enabled=true})}
function leaveLaptop(){laptopMode=false;panel.classList.remove('open');$('hero').classList.remove('hidden-ui');$('hint').classList.remove('hidden-ui');$('homeBtn').classList.add('hidden');screenTitle.classList.remove('visible');controls.enabled=false;tweenCamera(initialCam,initialTarget,1.05,()=>{controls.target.copy(initialTarget);controls.minDistance=4.5;controls.maxDistance=13;controls.minPolarAngle=.72;controls.maxPolarAngle=1.48;controls.enabled=true})}
function tweenCamera(p,t,d,onDone){cameraTween={fromPos:camera.position.clone(),toPos:p.clone(),fromTarget:controls.target.clone(),toTarget:t.clone(),start:performance.now(),duration:d*1000,onDone}}
function updateCameraTween(now){if(!cameraTween)return;let t=Math.min(1,(now-cameraTween.start)/cameraTween.duration),e=t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;camera.position.lerpVectors(cameraTween.fromPos,cameraTween.toPos,e);controls.target.lerpVectors(cameraTween.fromTarget,cameraTween.toTarget,e);camera.lookAt(controls.target);if(t>=1){const d=cameraTween.onDone;cameraTween=null;d?.()}}
function showLanguage(id,card){const l=languages.find(x=>x.id===id);if(!l)return;activeCard=card;$('panelIcon').src=`https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/${l.icon}`;$('panelTitle').textContent=l.name;$('panelCategory').textContent=l.category;$('panelDescription').textContent=l.desc;$('panelTags').innerHTML=l.tags.map(t=>`<span>${t}</span>`).join('');$('languageAccent').style.background=`linear-gradient(90deg,${l.color},#fff)`;panel.classList.add('open')}
function animate(){requestAnimationFrame(animate);const t=clock.getElapsedTime();updateCameraTween(performance.now());controls.update();interactiveCards.forEach((g,i)=>{const s=g.userData.hover?1.07:activeCard===g&&panel.classList.contains('open')?1.04:1;g.scale.lerp(new THREE.Vector3(s,s,s),.13);g.position.y=g.userData.baseY+Math.sin(t*1.15+i*.7)*.006});steam.forEach((p,i)=>{const u=(t*.18+p.userData.offset)%1;p.position.y=1.54+u*.95;p.position.x=-1.3+Math.sin(t*1.6+i)*(.02+u*.05);p.material.opacity=Math.sin(Math.PI*u)*.16;p.scale.setScalar(.8+u*2)});renderer.render(scene,camera)}
function onResize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.8))}
function startMusic(){if(musicOn)return;audioCtx||=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();ambientMaster=audioCtx.createGain();ambientMaster.gain.value=.12;ambientMaster.connect(audioCtx.destination);musicOn=true;$('musicBtn').textContent='♫';scheduleChord();musicTimer=setInterval(scheduleChord,7600)}
function scheduleChord(){if(!audioCtx||!musicOn)return;const chords=[[130.81,164.81,196,246.94],[110,138.59,164.81,207.65],[146.83,174.61,220,261.63],[98,123.47,146.83,185]],ch=chords[Math.floor((audioCtx.currentTime/7.6)%4)],now=audioCtx.currentTime;ch.forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),fl=audioCtx.createBiquadFilter();o.type=i?'triangle':'sine';o.frequency.value=f;fl.type='lowpass';fl.frequency.value=700;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(i?.022:.04,now+.35);g.gain.exponentialRampToValueAtTime(.0001,now+7.2);o.connect(fl);fl.connect(g);g.connect(ambientMaster);o.start(now);o.stop(now+7.4)})}
function toggleMusic(){if(!audioCtx){startMusic();return}if(musicOn){musicOn=false;clearInterval(musicTimer);ambientMaster?.gain.setTargetAtTime(.0001,audioCtx.currentTime,.08);$('musicBtn').textContent='♪'}else{ambientMaster?.disconnect();startMusic()}}